"use client";

import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ReportContent } from "@/types";

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <Card className="glass-card">
      <CardHeader className="pb-2">
        <CardTitle className="text-base">{title}</CardTitle>
      </CardHeader>
      <CardContent className="text-sm text-muted-foreground whitespace-pre-wrap">{children}</CardContent>
    </Card>
  );
}

function priorityVariant(priority: string) {
  if (priority === "high" || priority === "critical") return "destructive" as const;
  if (priority === "medium") return "warning" as const;
  return "secondary" as const;
}

export function ReportContentView({ content }: { content: ReportContent }) {
  return (
    <div className="space-y-6">
      <Section title="Executive Summary">{content.executive_summary}</Section>

      <div className="grid gap-4 lg:grid-cols-2">
        <Section title="SEO Summary">{content.seo_summary}</Section>
        <Section title="Performance Summary">{content.performance_summary}</Section>
        <Section title="Technical Summary">{content.technical_summary}</Section>
        <Section title="Opportunity Summary">{content.opportunity_summary}</Section>
      </div>

      {content.client_recommendations?.length > 0 && (
        <Card className="glass-card">
          <CardHeader className="pb-2">
            <CardTitle className="text-base">Client Recommendations</CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            {content.client_recommendations.map((rec, i) => (
              <div key={i} className="rounded-md border border-border/60 p-3">
                <div className="mb-1 flex items-center gap-2">
                  <Badge variant={priorityVariant(rec.priority)}>{rec.priority}</Badge>
                  <span className="font-medium text-sm">{rec.title}</span>
                </div>
                <p className="text-sm text-muted-foreground">{rec.description}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      )}

      <Card className="glass-card border-primary/20">
        <CardHeader className="pb-2">
          <CardTitle className="text-base">Sales Enablement</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          {content.cold_calling_talking_points?.length > 0 && (
            <div>
              <h3 className="mb-2 text-sm font-medium">Cold Calling Talking Points</h3>
              <ul className="list-disc space-y-1 pl-5 text-sm text-muted-foreground">
                {content.cold_calling_talking_points.map((point, i) => (
                  <li key={i}>{point}</li>
                ))}
              </ul>
            </div>
          )}
          {content.sales_pitch_summary && (
            <div>
              <h3 className="mb-2 text-sm font-medium">Sales Pitch Summary</h3>
              <p className="text-sm text-muted-foreground whitespace-pre-wrap">
                {content.sales_pitch_summary}
              </p>
            </div>
          )}
          {content.outreach_recommendations?.length > 0 && (
            <div>
              <h3 className="mb-2 text-sm font-medium">Outreach Recommendations</h3>
              <div className="space-y-2">
                {content.outreach_recommendations.map((item, i) => (
                  <div key={i} className="rounded-md bg-muted/40 p-3 text-sm">
                    <div className="mb-1 flex items-center gap-2">
                      <Badge variant="outline">{item.channel}</Badge>
                      <span className="text-xs text-muted-foreground">{item.timing}</span>
                    </div>
                    <p className="text-muted-foreground">{item.message}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {content.metadata?.generated_by && (
        <p className="text-xs text-muted-foreground">
          Generated by {content.metadata.generated_by}
          {content.metadata.model ? ` (${content.metadata.model})` : ""}
        </p>
      )}
    </div>
  );
}
